language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master

#before_script: mvn versions:set -DnewVersion=1.0.1

script:
  - mvn -q clean install

# after_success: mvn versions:set -DnewVersion=1.0.2-SNAPSHOT
